AWSTemplateFormatVersion: "2010-09-09"
Description: AnswerNow - Database Stack (Postgres RDS in private subnets)

Parameters:
  VpcId:
    Type: String
    Default: vpc-0e19b6b5a3b3ffecf

  PrivateSubnet1Id:
    Type: String
    Default: subnet-0c3dd7b54240a5b4b

  PrivateSubnet2Id:
    Type: String
    Default: subnet-0c5f1f239704e31d8

  RdsSecurityGroupId:
    Type: String
    Default: sg-0483cb81e96e86539

  DbName:
    Type: String
    Default: answernowdb

  DbMasterUsername:
    Type: String
    Default: answernowadmin
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9_]*$"

  DbMasterPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41

  DbInstanceClass:
    Type: String
    Default: db.t4g.micro
    AllowedValues:
      - db.t4g.micro
      - db.t3.micro

  AllocatedStorageGb:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 100

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: AnswerNow DB subnet group (private subnets)
      SubnetIds:
        - Ref: PrivateSubnet1Id
        - Ref: PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: answernow-db-subnet-group-dev

  AnswerNowPostgres:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceIdentifier: answernow-postgres-dev
      DBName:
        Ref: DbName
      MasterUsername:
        Ref: DbMasterUsername
      MasterUserPassword:
        Ref: DbMasterPassword
      DBInstanceClass:
        Ref: DbInstanceClass
      AllocatedStorage:
        Ref: AllocatedStorageGb
      StorageType: gp3
      PubliclyAccessible: false
      MultiAZ: false
      StorageEncrypted: true
      BackupRetentionPeriod: 1
      DeletionProtection: false
      VPCSecurityGroups:
        - Ref: RdsSecurityGroupId
      DBSubnetGroupName:
        Ref: DbSubnetGroup

Outputs:
  DbEndpoint:
    Description: RDS endpoint hostname
    Value:
      Fn::GetAtt: [AnswerNowPostgres, Endpoint.Address]

  DbPort:
    Description: RDS port
    Value:
      Fn::GetAtt: [AnswerNowPostgres, Endpoint.Port]

  DbName:
    Description: Database name
    Value:
      Ref: DbName

  DbInstanceIdentifier:
    Description: DB Instance Identifier
    Value:
      Ref: AnswerNowPostgres
