AWSTemplateFormatVersion: "2010-09-09"
Description: AnswerNow - Database Stack (PROD) - Postgres RDS in private subnets

Parameters:
  VpcId:
    Type: String
    Description: VPC Id for the database

  PrivateSubnet1Id:
    Type: String
    Description: Private Subnet 1 Id

  PrivateSubnet2Id:
    Type: String
    Description: Private Subnet 2 Id

  RdsSecurityGroupId:
    Type: String
    Description: Security group that allows Postgres inbound (usually from Lambda SG)

  DbName:
    Type: String
    Default: answernowdb

  DbMasterUsername:
    Type: String
    Default: answernowadmin
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "^[a-zA-Z][a-zA-Z0-9_]*$"

  DbMasterPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 41

  DbInstanceClass:
    Type: String
    Default: db.t4g.micro
    AllowedValues:
      - db.t4g.micro
      - db.t3.micro

  AllocatedStorageGb:
    Type: Number
    Default: 20
    MinValue: 20
    MaxValue: 200

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: AnswerNow DB subnet group (private subnets)
      SubnetIds:
        - Ref: PrivateSubnet1Id
        - Ref: PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: answernow-db-subnet-group-prod
        - Key: Project
          Value: AnswerNow
        - Key: Environment
          Value: prod
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Owner
          Value: Jason

  AnswerNowPostgres:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceIdentifier: answernow-postgres-prod
      DBName:
        Ref: DbName
      MasterUsername:
        Ref: DbMasterUsername
      MasterUserPassword:
        Ref: DbMasterPassword
      DBInstanceClass:
        Ref: DbInstanceClass
      AllocatedStorage:
        Ref: AllocatedStorageGb
      StorageType: gp3

      # Production-ish defaults (still cost-conscious)
      PubliclyAccessible: false
      MultiAZ: false
      StorageEncrypted: true
      BackupRetentionPeriod: 7
      DeletionProtection: true

      VPCSecurityGroups:
        - Ref: RdsSecurityGroupId
      DBSubnetGroupName:
        Ref: DbSubnetGroup

      Tags:
        - Key: Name
          Value: answernow-postgres-prod
        - Key: Project
          Value: AnswerNow
        - Key: Environment
          Value: prod
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Owner
          Value: Jason

Outputs:
  DbEndpoint:
    Description: RDS endpoint hostname
    Value:
      Fn::GetAtt: [AnswerNowPostgres, Endpoint.Address]

  DbPort:
    Description: RDS port
    Value:
      Fn::GetAtt: [AnswerNowPostgres, Endpoint.Port]

  DbName:
    Description: Database name
    Value:
      Ref: DbName

  DbInstanceIdentifier:
    Description: DB Instance Identifier
    Value:
      Ref: AnswerNowPostgres

  DbConnectionString:
    Description: Connection string (no password)
    Value: !Sub "Host=${AnswerNowPostgres.Endpoint.Address};Port=${AnswerNowPostgres.Endpoint.Port};Database=${DbName};Username=${DbMasterUsername};SSL Mode=Require;Trust Server Certificate=true"
