AWSTemplateFormatVersion: '2010-09-09'
Description: AnswerNow Operational Stack - Budgets, SNS Notifications, and CloudWatch Monitoring

Parameters:
  EnvName:
    Type: String
    AllowedValues: [dev, qa, prod]
    Description: Deployment environment

  AlertEmail:
    Type: String
    Description: Email address for operational alerts

  AlertPhoneE164:
    Type: String
    Description: Phone number in E.164 format (example +12085551234)

  MonthlyBudgetLimitUsd:
    Type: Number
    Default: 25
    Description: Monthly AWS budget limit in USD

  HttpApiId:
    Type: String
    Description: HTTP API Id (ApiGatewayV2)

  HttpApiStageName:
    Type: String
    Default: "$default"
    Description: HTTP API stage name

  LambdaFunctionName:
    Type: String
    Description: Lambda function name (FunctionName dimension)

  RdsDbInstanceIdentifier:
    Type: String
    Default: ""
    Description: RDS DBInstanceIdentifier (leave empty if not deployed)

  RdsFreeStorageThresholdBytes:
    Type: Number
    Default: 5368709120
    Description: Free storage threshold in bytes for RDS alarm

Conditions:
  HasRds: !Not [!Equals [!Ref RdsDbInstanceIdentifier, ""]]

Resources:
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub answernow-${EnvName}-alerts

  AlarmTopicEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  AlarmTopicSmsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: sms
      Endpoint: !Ref AlertPhoneE164

  MonthlyCostBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub answernow-${EnvName}-monthly-budget
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: !Ref MonthlyBudgetLimitUsd
          Unit: USD
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            ThresholdType: PERCENTAGE
            Threshold: 80
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            ThresholdType: PERCENTAGE
            Threshold: 100
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail

  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-lambda-errors
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

  LambdaThrottlesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-lambda-throttles
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

  HttpApi5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-httpapi-5xx
      Namespace: AWS/ApiGateway
      MetricName: 5xx
      Dimensions:
        - Name: ApiId
          Value: !Ref HttpApiId
        - Name: Stage
          Value: !Ref HttpApiStageName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

  RdsCpuHighAlarm:
    Condition: HasRds
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-rds-cpu-high
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RdsDbInstanceIdentifier
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

  RdsFreeStorageLowAlarm:
    Condition: HasRds
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-rds-free-storage-low
      Namespace: AWS/RDS
      MetricName: FreeStorageSpace
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RdsDbInstanceIdentifier
      Statistic: Minimum
      Period: 300
      EvaluationPeriods: 2
      Threshold: !Ref RdsFreeStorageThresholdBytes
      ComparisonOperator: LessThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

Outputs:
  AlarmTopicArn:
    Description: SNS topic ARN for operational alerts
    Value: !Ref AlarmTopic
