AWSTemplateFormatVersion: '2010-09-09'
Description: AnswerNow Operational Stack - Budgets, SNS Notifications, and CloudWatch Monitoring

Parameters:
  EnvName:
    Type: String
    AllowedValues: [dev, qa, prod]
    Description: Deployment environment

  AlertEmail:
    Type: String
    Description: Email address for operational alerts

  AlertPhoneE164:
    Type: String
    Description: Phone number in E.164 format (example +12085551234)

  MonthlyBudgetLimitUsd:
    Type: Number
    Default: 25
    Description: Monthly AWS budget limit in USD

  LambdaFunctionName:
    Type: String
    Description: Lambda function name to monitor (e.g., answernow-api-prod)

  HttpApiId:
    Type: String
    Description: API Gateway HTTP API id to monitor (e.g., xw4nmbbm2h)

  HttpApiStageName:
    Type: String
    Default: $default
    Description: HTTP API stage name

  RdsDbInstanceIdentifier:
    Type: String
    Default: ""
    Description: RDS DBInstanceIdentifier (leave empty if not deployed)

  RdsFreeStorageThresholdBytes:
    Type: Number
    Default: 5368709120
    Description: Free storage threshold in bytes for RDS alarm (default 5GB)

Conditions:
  HasRds: !Not [!Equals [!Ref RdsDbInstanceIdentifier, ""]]

Resources:

  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub answernow-${EnvName}-alerts
      Tags:
        - Key: Project
          Value: AnswerNow
        - Key: Environment
          Value: !Ref EnvName
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Owner
          Value: Jason

  AlarmTopicEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  AlarmTopicSmsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlarmTopic
      Protocol: sms
      Endpoint: !Ref AlertPhoneE164

  MonthlyCostBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub answernow-${EnvName}-monthly-budget
        BudgetType: COST
        TimeUnit: MONTHLY
        BudgetLimit:
          Amount: !Ref MonthlyBudgetLimitUsd
          Unit: USD
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            ThresholdType: PERCENTAGE
            Threshold: 80
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail
        - Notification:
            NotificationType: ACTUAL
            ComparisonOperator: GREATER_THAN
            ThresholdType: PERCENTAGE
            Threshold: 100
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref AlertEmail

  # -----------------------------
  # Lambda alarms
  # -----------------------------

  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-lambda-errors
      AlarmDescription: "Lambda Errors > 0 (5 min)"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic

  LambdaThrottlesAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-lambda-throttles
      AlarmDescription: "Lambda Throttles > 0 (5 min)"
      Namespace: AWS/Lambda
      MetricName: Throttles
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

  LambdaDurationP95Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-lambda-duration-p95
      AlarmDescription: "Lambda Duration p95 > 2000ms (5 min)"
      Namespace: AWS/Lambda
      MetricName: Duration
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      ExtendedStatistic: p95
      Period: 300
      EvaluationPeriods: 1
      Threshold: 2000
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

  # -----------------------------
  # HTTP API alarms
  # -----------------------------

  HttpApi5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-httpapi-5xx
      AlarmDescription: "HTTP API 5XX errors > 0 (5 min)"
      Namespace: AWS/ApiGateway
      MetricName: 5XXError
      Dimensions:
        - Name: ApiId
          Value: !Ref HttpApiId
        - Name: Stage
          Value: !Ref HttpApiStageName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

  # -----------------------------
  # RDS alarms (optional)
  # -----------------------------

  RdsCpuHighAlarm:
    Condition: HasRds
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-rds-cpu-high
      AlarmDescription: "RDS CPU > 70% (10 min)"
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RdsDbInstanceIdentifier
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

  RdsFreeStorageLowAlarm:
    Condition: HasRds
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub answernow-${EnvName}-rds-free-storage-low
      AlarmDescription: "RDS FreeStorageSpace low"
      Namespace: AWS/RDS
      MetricName: FreeStorageSpace
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref RdsDbInstanceIdentifier
      Statistic: Minimum
      Period: 300
      EvaluationPeriods: 2
      Threshold: !Ref RdsFreeStorageThresholdBytes
      ComparisonOperator: LessThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic

Outputs:
  AlarmTopicArn:
    Description: SNS topic ARN for operational alerts
    Value: !Ref AlarmTopic
